# ALL KEYS SHOULD BE LOWERCASE
WikiLinks = {
	# BLOCKS


	# VANITY
	"aviators" : "https://terraria.wiki.gg/wiki/0x33%27s_Aviators",
	"badger's": "https://terraria.wiki.gg/wiki/Badger%27s_Hat",
	"badgers": "https://terraria.wiki.gg/wiki/Badger%27s_Hat",
	"balla": "https://terraria.wiki.gg/wiki/Balla_Hat",
	"beanie": "https://terraria.wiki.gg/wiki/Beanie",
	"bunny hood": "https://terraria.wiki.gg/wiki/Bunny_Hood",
	"cat ears": "https://terraria.wiki.gg/wiki/Cat_Ears",
	"dead man's sweater": "https://terraria.wiki.gg/wiki/Dead_Man%27s_Sweater",
	"dead mans sweater": "https://terraria.wiki.gg/wiki/Dead_Man%27s_Sweater",
	"dead man sweater": "https://terraria.wiki.gg/wiki/Dead_Man%27s_Sweater",
	"demon horn": "https://terraria.wiki.gg/wiki/Demon_Horns",
	"devil horn": "https://terraria.wiki.gg/wiki/Devil_Horns",
	"dizzy's" : "https://terraria.wiki.gg/wiki/Dizzy%27s_Rare_Gecko_Chester",
	"gecko": "https://terraria.wiki.gg/wiki/Dizzy%27s_Rare_Gecko_Chester",
	"chester": "https://terraria.wiki.gg/wiki/Dizzy%27s_Rare_Gecko_Chester",
	"engineering helmet": "https://terraria.wiki.gg/wiki/Engineering_Helmet",
	"engineer helmet" : "https://terraria.wiki.gg/wiki/Engineering_Helmet",
	"eye patch": "https://terraria.wiki.gg/wiki/Eye_Patch",
	"eyebrella": "https://terraria.wiki.gg/wiki/Eyebrella",
	"fedora": "https://terraria.wiki.gg/wiki/Fedora",
	"fez" : "https://terraria.wiki.gg/wiki/Fez",
	"gangsta" : "https://terraria.wiki.gg/wiki/Gangsta_Hat",
	"garland": "https://terraria.wiki.gg/wiki/Garland",
	"bow": "https://terraria.wiki.gg/wiki/Giant_Bow",
	"goblorc": "https://terraria.wiki.gg/wiki/Goblorc_Ears",
	"gold crown": "https://terraria.wiki.gg/wiki/Gold_Crown",
	"fawkes": "https://terraria.wiki.gg/wiki/Guy_Fawkes_Mask",
	"heart hairpin": "https://terraria.wiki.gg/wiki/Heart_Hairpin",
	"hitek": "https://terraria.wiki.gg/wiki/HiTek_Sunglasses",
	"lantern mask": "https://terraria.wiki.gg/wiki/Jack_%27O_Lantern_Mask",
	"jim's cap": "https://terraria.wiki.gg/wiki/Jim%27s_Cap",
	"jims cap": "https://terraria.wiki.gg/wiki/Jim%27s_Cap",
	"kimono" : "https://terraria.wiki.gg/wiki/Kimono",
	"mime": "https://terraria.wiki.gg/wiki/Mime_Mask",
	"moon mask": "https://terraria.wiki.gg/wiki/Moon_Mask",
	"mushroom cap": "https://terraria.wiki.gg/wiki/Mushroom_Cap",
	"mushroom hat": "https://terraria.wiki.gg/wiki/Mushroom_Cap",
	"panda ears": "https://terraria.wiki.gg/wiki/Panda_Ears",
	"party hat": "https://terraria.wiki.gg/wiki/Party_Hat",
	"peddler's hat": "https://terraria.wiki.gg/wiki/Peddler%27s_Hat",
	"peddlers hat": "https://terraria.wiki.gg/wiki/Peddler%27s_Hat",
	"peddler hat": "https://terraria.wiki.gg/wiki/Peddler%27s_Hat",
	"platinum crown": "https://terraria.wiki.gg/wiki/Platinum_Crown",
	"rabbit perch": "https://terraria.wiki.gg/wiki/Rabbit_Perch",
	"antlers": "https://terraria.wiki.gg/wiki/Reindeer_Antlers",
	"robe": "https://terraria.wiki.gg/wiki/Robe",
	"quote hat": "https://terraria.wiki.gg/wiki/Robot_Hat",
	"robot hat": "https://terraria.wiki.gg/wiki/Robot_Hat",
	"swat helmet": "https://terraria.wiki.gg/wiki/SWAT_Helmet",
	"police helmet": "https://terraria.wiki.gg/wiki/SWAT_Helmet",
	"skull": "https://terraria.wiki.gg/wiki/Skull",
	"snow hat": "https://terraria.wiki.gg/wiki/Snow_Hat",
	"star hairpin": "https://terraria.wiki.gg/wiki/Star_Hairpin",
	"steampunk goggles": "https://terraria.wiki.gg/wiki/Steampunk_Goggles",
	"summer hat": "https://terraria.wiki.gg/wiki/Summer_Hat",
	"sun mask": "https://terraria.wiki.gg/wiki/Sun_Mask",
	"sunglasses": "https://terraria.wiki.gg/wiki/Sunglasses",
	"shanter": "https://terraria.wiki.gg/wiki/Tam_O%27_Shanter",
	"ugly sweater": "https://terraria.wiki.gg/wiki/Ugly_Sweater",
	"umbrella hat": "https://terraria.wiki.gg/wiki/Umbrella_Hat",
	"vulkelf ears":"https://terraria.wiki.gg/wiki/Vulkelf_Ears",
	"wizard's hat": "https://terraria.wiki.gg/wiki/Wizard%27s_Hat",
	"wizards hat": "https://terraria.wiki.gg/wiki/Wizard%27s_Hat",
	# SETS
	"bride of frankenstein": "https://terraria.wiki.gg/wiki/Bride_of_Frankenstein_set",
	"bride of frankenstien": "https://terraria.wiki.gg/wiki/Bride_of_Frankenstein_set",
	"cat set": "https://terraria.wiki.gg/wiki/Cat_set",
	"cat mask": "https://terraria.wiki.gg/wiki/Cat_set",
	"cat shirt": "https://terraria.wiki.gg/wiki/Cat_set",
	"cat pants": "https://terraria.wiki.gg/wiki/Cat_set",
	"cat costume": "https://terraria.wiki.gg/wiki/Cat_set",
	"clothier set": "https://terraria.wiki.gg/wiki/Clothier%27s_set",
	"clothiers set": "https://terraria.wiki.gg/wiki/Clothier%27s_set",
	"clothier's set": "https://terraria.wiki.gg/wiki/Clothier%27s_set",
	"clothier hat": "https://terraria.wiki.gg/wiki/Clothier%27s_set",
	"clothiers hat": "https://terraria.wiki.gg/wiki/Clothier%27s_set",
	"clothier's hat": "https://terraria.wiki.gg/wiki/Clothier%27s_set",
	"red hat": "https://terraria.wiki.gg/wiki/Clothier%27s_set",
	"clothier jacket": "https://terraria.wiki.gg/wiki/Clothier%27s_set",
	"clothiers jacket": "https://terraria.wiki.gg/wiki/Clothier%27s_set",
	"clothier's jacket": "https://terraria.wiki.gg/wiki/Clothier%27s_set",
	"clothier's pants": "https://terraria.wiki.gg/wiki/Clothier%27s_set",
	"clothiers pants": "https://terraria.wiki.gg/wiki/Clothier%27s_set",
	"clothier pants": "https://terraria.wiki.gg/wiki/Clothier%27s_set",
	"creeper set": "https://terraria.wiki.gg/wiki/Creeper_set",
	"creeper mask": "https://terraria.wiki.gg/wiki/Creeper_set",
	"creeper shirt": "https://terraria.wiki.gg/wiki/Creeper_set",
	"creeper pants": "https://terraria.wiki.gg/wiki/Creeper_set",
	"creeper costume": "https://terraria.wiki.gg/wiki/Creeper_set",


	# ARMOR
	"wizard hat": "https://terraria.wiki.gg/wiki/Wizard_Hat",

	# BOTH
	"fish bowl" : "https://terraria.wiki.gg/wiki/Fish_Bowls",
	"serpent bowl": "https://terraria.wiki.gg/wiki/Fish_Bowls",
	"golem head": "https://terraria.wiki.gg/wiki/Rock_Golem_Head",


	# DESPERATION ~ VANITY
	"sweater" : ["https://terraria.wiki.gg/wiki/Dead_Man%27s_Sweater", "https://terraria.wiki.gg/wiki/Ugly_Sweater"],
	"eye": ["https://terraria.wiki.gg/wiki/Eye_Patch", "https://terraria.wiki.gg/wiki/Eyebrella", "https://terraria.wiki.gg/wiki/Masks#Eye_of_Cthulhu_Mask"],
	"crown": ["https://terraria.wiki.gg/wiki/Platinum_Crown", "https://terraria.wiki.gg/wiki/Gold_Crown"],
	"ears": ["https://terraria.wiki.gg/wiki/Goblorc_Ears", "https://terraria.wiki.gg/wiki/Cat_Ears", "https://terraria.wiki.gg/wiki/Panda_Ears", "https://terraria.wiki.gg/wiki/Vulkelf_Ears"],
	"hairpin": ["https://terraria.wiki.gg/wiki/Heart_Hairpin", "https://terraria.wiki.gg/wiki/Seashell_Hairpin", "https://terraria.wiki.gg/wiki/Star_Hairpin"]
}